name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v4
      with:
        version: latest
        python-version: "3.12"
        enable-cache: true

    - name: Get version
      id: version
      run: |
        PROJECT_VERSION=$(uv version --short)
        TAG_VERSION=${GITHUB_REF#refs/tags/v}
        echo "PROJECT_VERSION=$PROJECT_VERSION" >> $GITHUB_OUTPUT
        echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_OUTPUT
        echo "Project version: $PROJECT_VERSION"
        echo "Tag version: $TAG_VERSION"

    - name: Verify version
      if: steps.version.outputs.PROJECT_VERSION != steps.version.outputs.TAG_VERSION
      run: exit 1

    - name: Build
      run: uv build

    - name: Publish to PyPI
      run: uv publish
